### ISSUE TITLE
The Chromebook extension will not download

### ISSUE THREAD

**Issue by raysalemi** [arduino/help-center-content#119]
[Using Arduino with Chromebook
](https://support.arduino.cc/hc/en-us/articles/360016495639-Use-Arduino-with-Chromebook)A link to the published article.

The article points you to the Chrome Store to install the Arduino Chrome Extension, but the *Add to Chrome* button fails.  The dialog box says, "Download interrupted," and the file `elmgohdonjdamp...crx` does not exist. The message says `Failed -- no file.`

I've tested this behavior on two Macs and gotten the same result.

**Comment by seaxwi** [comment]
The Arduino Create for Education Chrome App can only be added on Chrome OS. Admittingly it is confusing that the page will say "Compatible with your device" anyway, and the error output isn't very informative.

If you want to use Arduino Cloud with Mac you need to install the [Arduino Create Agent](https://create.arduino.cc/getting-started/plugin/welcome).
