### ISSUE TITLE
Wiring between UNO and Nano using `RESET` and `10` pins appears to be inverted

### ISSUE THREAD

**Issue by lalugue** [arduino/help-center-content#122]
**Article URL**

https://support.arduino.cc/hc/en-us/articles/4841602539164-Burn-the-bootloader-on-UNO-Mega-and-classic-Nano-using-another-Arduino

**Describe the problem with the article**

In the diagram displaying the wiring between the UNO and Nano (in the section: `Option A: Using the digital and power pins`), the UNO's `RESET` pin connects to the Nano's `10` pin; the image description also indicates the UNO as the programmer board:

![image](https://user-images.githubusercontent.com/51893731/193413453-d32f82a3-326b-4aa5-ab6d-04da9c311b3a.png)

However, based on the table above the diagram, the programmer board's `PIN 10` pin should be connected to the target board's `RESET` pin:

![image](https://user-images.githubusercontent.com/51893731/193413589-45be027d-a074-430b-baf5-d8e31362ed1c.png)

In this case, it looks like the UNO/programmer board's `PIN 10` in the image should be connected to the Nano/target board's `RESET` pin instead (or perhaps the Nano in the image should be indicated as the board programming the UNO instead); wiring the two boards first-hand this way appears to confirm the case too

**Comment by seaxwi** [comment]
@lalugue Thank you for reporting this issue. I've added a new connection diagram in this PR https://github.com/arduino/help-center-content/pull/123
