### ISSUE TITLE
Contradictory information re: title format

### ISSUE THREAD

**Issue by per1234** [arduino/help-center-content#171]
The project's wiki specifies the required format for the article title:

https://github.com/arduino/help-center-content/wiki/Markdown-style-and-conventions#front-matter

This contains errors:

>The title should be written in TitleCase

There is no such term as "TitleCase". The correct term is "title case":

https://en.wikipedia.org/wiki/Title_case

This is more than a nitpick. Mashing the words together in this way indicates to the reader that spaces should be omitted from the title text (["CamelCase"](https://en.wikipedia.org/wiki/Camel_case)).

>i.e only the first word is capitalized, except for 'Arduino', product names, etc.

This is an incorrect description for title case. The description is of "sentence case":

https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case

**Comment by seaxwi** [comment]
Thanks @per1234. The current convention is in fact sentence case. I have updated the wiki.
